### ISSUE TITLE
[Operations] Dockerize application

### ISSUE THREAD

**Issue by Elektropepi** [Debugger-Buam/Funkgeraet#32]
Dockerize both client and server and build them with github actions, so the application can be brought to production more easily

- [x] Implement client and server docker build with docker-compose on branch `feature/dockerize-application`
- [x] replace .env with a variant to supply web socket url and turn server via environment variable when starting container (then also adapt README and replace ports with environment variables)
- [x] Setup github actions to build and publish docker containers on ghcr.io and replace old CI actions
- [x] ~implement Hash URLs: https://github.com/Debugger-Buam/Funkgeraet/issues/33~

**Comment by maperz** [comment]
Both `backend-ci.yml` and `frontend-ci.yml` received a facelift and now publish docker images to the ghcr account specified by `secrets.GHCR_USERNAME` and `secrets.GHCR_PASSWORD`.

- [x] Replace GHCR credentials with Organisation/Repo credential instead of my PAT.
- [x] Make use of env variables as stated in OP.
- [ ] Find a way to publish an ARM image to be used on a raspberry pi, as currently built times on raspberry pi run 15min and longer.
- [x] Adapt the workflow files to only publish on master push/pull requests.

**Comment by maperz** [comment]
![image](https://user-images.githubusercontent.com/12886164/103521965-f0080980-4e79-11eb-9720-373cf446df13.png)
When configured properly, images should be listed under repository packages.

**Comment by Elektropepi** [comment]
@maperz looks like your TODOs are done too. I've now implemented supplying environment variables on runtime.
